# docker run --rm -e "JEKYLL_ENV=docker" -v "C:\Users\ddw\Desktop\Dockerfiles\jekyll\worncassettes:/srv/jekyll" -p 0.0.0.0:4000:4000 jekyll/jekyll jekyll serve

version: '3'
services: 
  jekyll-serve:
    environment:
      - JEKYLL_ENV=docker
    image: jekyll/jekyll
    volumes:
      - '.:/srv/jekyll'
    ports:
      - 4000:4000
    command: 'jekyll serve --watch --incremental --force_polling'

